/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.gltf
Author: MaxNRG (https://sketchfab.com/MaxNRG)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/belyash-a39209c0eb804a7da887777fd48f8c98
Title: Belyash
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.MI_Belyash_Body} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.MI_Belyash_Head} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.M_Emiss_Inst} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
